version: 2
updates:
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  reviewers:
  - alcutter
  ignore:
  - dependency-name: github.com/otiai10/copy
    versions:
    - 1.4.2
  - dependency-name: github.com/google/go-cmp
    versions:
    - 0.5.4
