// Copyright 2021 Google Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package licenses

import (
	"fmt"
	"io/fs"
	"os"
	"path/filepath"

	"github.com/google/go-licenses/v2/gocli"
)

// License is an open source software license.
type License struct {
	ID   string // SPDX ID. https://spdx.org/licenses.
	Path string // Relative path in the module.
	URL  string // Optional, license file URL on internet.
}

// Module is a go module with license info.
// There can be multiple licenses, because of several different reasons.
// Some common reasons include:
// * Modules may vendor internal packages of other modules. The vendored packages have a different license.
// * Modules may be rewritten from source code of a different langugage. Both
// the original license and the new license applies to the code.
// * Extra files may be false-positives of the license classifier. So you should
// verify the results generated by this tool.
type Module struct {
	gocli.Module
	Licenses []License
}

var ErrorEmptyDir = fmt.Errorf("dir is empty")

// Scan scans a module for licenses.
func Scan(m gocli.Module, classifier Classifier) (res Module, err error) {
	defer func() {
		if err != nil {
			err = fmt.Errorf("scanning licenses for module %q: %w", m.Path, err)
		}
	}()
	res.Module = m
	if m.Dir == "" {
		return res, ErrorEmptyDir
	}
	res.Licenses = make([]License, 0)
	err = filepath.Walk(m.Dir, func(path string, info fs.FileInfo, err error) error {
		if err != nil {
			return err
		}
		if info.Mode()&os.ModeSymlink != 0 {
			// skip symbolic links
			return nil
		}
		if info.IsDir() {
			if ignoredDir[info.Name()] {
				return filepath.SkipDir
			}
			return nil
		}
		if !licenseRegexp.MatchString(info.Name()) {
			// Skip file names that does not look like a license file.
			return nil
		}
		licenseID, _, err := classifier.Identify(path)
		if err != nil {
			// It's expected for files without license text in it.
			return nil
		}
		res.Licenses = append(res.Licenses, License{
			ID:   licenseID,
			Path: path,
		})
		return nil
	})
	if len(res.Licenses) == 0 {
		return res, fmt.Errorf("license not found")
	}
	return res, err
}

var ignoredDir map[string]bool = make(map[string]bool)

func init() {
	ignoredDir[".git"] = true
	ignoredDir["node_modules"] = true
	ignoredDir["testdata"] = true
}
